services:
  - type: web
    name: portfolio-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CONTACT_RECEIVE_EMAIL
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GMAIL_TOKEN
        sync: false
      - key: CORS_ORIGINS
        sync: false
